### ISSUE TITLE
Define acceptable library versions

### ISSUE THREAD

**Issue by tsalo** [NBCLab/stranger-things-task#5]
I believe we need the following:

- pyglet 1.2.4
- psychopy 1.84-1.90 (not 2+)
- What about Python?

**Comment by adamkimbler** [comment]
Psychopy 1.80 - 1.90 should work, 1.90 is the newest non-python 3 version
The most important thing is that `pyglet` should be no later than version 1.2.4
Python version 2.7 or greater should work in all cases

**Comment by tsalo** [comment]
Do you want to add a Requirements section to the README or would you rather I do it?
